### ISSUE TITLE
Potentially real account number used as example

### ISSUE THREAD

**Issue by mwedgwood-rmn** [RetailMeNotSandbox/ecs-selenium#1]
https://github.com/RetailMeNotSandbox/ecs-selenium/blob/510c83767dee0c0738beda9f8d336acde73faec5/docker/ecs-node-chrome/Makefile#L3

123412341234 could be real. 111122223333 is known to be reserved for documentation. This also appears in the node-firefox Makefile.

**Comment by robertoriv** [comment]
Updated.

Thanks!
