### ISSUE TITLE
Latest versions failing

### ISSUE THREAD

**Issue by thetemplateblog** [RetailMeNotSandbox/ecs-selenium#15]
Have you tested this with VERSION > 3.11.0?

I am getting this error
`18:36:45.956 ERROR [SeleniumServer.boot] - Port 5555 is busy, please choose a free port and specify it using -port option`

I believe it is related to [THIS](https://github.com/SeleniumHQ/docker-selenium/issues/742)

Any thoughts?

**Comment by rrivera-rmn** [comment]
@thetemplateblog,

We are currently running `3.11.0` in our environment. And I had a change for this that hadn't made it to master (remove the `-host` parameter).

Give it a shot with the latest version. (Which also bumps the nodes to `3.14.0`)

Thanks for reporting this.
