### ISSUE TITLE
[Request] Update to latest version

### ISSUE THREAD

**Issue by ankitsam** [RetailMeNotSandbox/ecs-selenium#19]
Latest selenium node images (3.141.XX) supports xvfb etc.

**Comment by Voldiemert** [comment]
In the make files located in `docker/ecs-node-chrome` and `docker/ecs-node-firefox` you can change the `ARG` parameter to be `ARG=latest` to use the latest version.

**Comment by Voldiemert** [comment]
> Latest selenium node images (3.141.XX) supports xvfb etc.

In the make files located in `docker/ecs-node-chrome` and `docker/ecs-node-firefox` you can change the `ARG` parameter to be `ARG=latest` to use the latest version.

**Comment by averkamp-rmn** [comment]
I have gone ahead and made a few changes to the repo.

I have updated the docker files to follow latest. 
I have bumped the version number in the make files to reflect what was available as of Friday in the make file.
I have also changed variable names to more match what is in the sample.env .
