### ISSUE TITLE
Update to -remoteHost problem

### ISSUE THREAD

**Issue by mbruning24** [RetailMeNotSandbox/ecs-selenium#3]
Now that the PR discussed in the documentation has been resolved, and it seems `-remoteHost` can be passed via `SE_OPTS` (https://github.com/SeleniumHQ/docker-selenium/issues/540) can we get an update of the repo?

Building selenium has been giving me lots of problems, seems like I get 95% through the build and it fails on "ActiveSessionFactory.java uses or overrides a deprecated API"

(a workaround for that would do nicely too)

**Comment by mbruning24** [comment]
noticed SE_OPTS was in the entry_point.sh file, so ignore that, but still is there a way to get a version bump so we don't have to build selenium locally?

**Comment by robertoriv** [comment]
Hi @mbruning24, 

Sorry it took me a few days to get to this. I've updated the base images to `3.8.1` which are the latest. I haven't been able to test them yet in a real environment.

Let me know if there are any issues.
