### ISSUE TITLE
Error while passing multiple subnet ids from parameter

### ISSUE THREAD

**Issue by Galileo1** [RetailMeNotSandbox/ecs-selenium#4]
Error message - type: <type 'list'>, valid types: <type 'basestring'>

I have tried everything Type= "List", CommaSepratedList,
and I have tried parameter passing like = ParameterKey=SubnetIds,ParameterValue=\"subnetis-xxx,subnetis-xxx\"

or ParameterKey=SubnetIds,ParameterValue="subnetis-xxx,subnetis-xxx"

It doesn't work

**Comment by rrivera-rmn** [comment]
Hi @Galileo1,

I think I messed up that example. 

https://aws.amazon.com/premiumsupport/knowledge-center/multiple-values-list-parameter-cli/

Looks like I need to escape the quotes on the list: `ParameterKey=SubnetIds,ParameterValue=\"<subnet--########>,<subnet-########>,...\"`

Let me know if that works and I'll update the docs accordingly.

**Comment by elijahchancey** [comment]
I had the same issue. Escaping the quotes fixed the issue. I already updated the docs in my PR to fix this.

**Comment by robertoriv** [comment]
This has been addressed in PR #5. Thanks @elijahchancey!
